apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellogirl
  namespace: lasample
  labels:
    app: hellogirl
spec:
  selector:
    matchLabels:
      app: hellogirl
  template:
    metadata:
      labels:
        app: hellogirl
    spec:
      containers:
      - name: hellogirl
        image: linuxacademycontent/gitops:hellov1.1
