name: Python application

on:
# The workflow will be triggered by every commit.
#  push:
#    paths:
#    - 'python/*'
    
# The workflow will be triggered by every Pull Request.
  pull_request:
    paths:
    - 'python/*'
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./python/requirements.txt
    - name: Build & Push Image
      run: |
        cd ./python
        echo "${{ secrets.DOCKERPW }}" | docker login -u dockertienphan --password-stdin
        docker image build -t dockertienphan/gitops:hellov1.0 .
        docker push dockertienphan/gitops:hellov1.0
